### ISSUE TITLE
Connect To Stored Network - Issue with Space in Name

### ISSUE THREAD

**Issue by MichaelRPowell** [XK9274/better-wifi-miyoo#1]
I have two networks. Let's say they are called Home and Home Upstairs. When looking at the list of stored networks to connect to, both options only say "Home". The same is true after selecting one, it says it is "Connecting to Home". If I look at the Stored Networks list, I can see which is which in the list of networks. So I can tell the second one listed is "Home Upstairs" even though it only says "Home".

Just a tiny bug for anyone using multiple networks with spaces in the name.

Thank you for the great tool. It is much better than the default wireless interface.

**Comment by XK9274** [comment]
Aye i'm aware of this one.. I had a hotspot called "Moto G" but only see "Moto" when i was testing. On my list of things to fix but with us potentially looking at building some of these features into Onion I'm not sure i'll end up doing it. If i ever decide to bundle this up for stock OS users i'll probably look at doing it then. That said i don't think there's many reasons to use Stock when there's a bunch of other good OS's to use if Onion isn't your cup of tea. (Allium, Koriki, DotUI etc) 😅

**Comment by MichaelRPowell** [comment]
All good! I appreciate the program you made. Just wanted to point out the one issue if you were still doing updates to it. Though I believe I read somewhere that wireless networks with spaces or special characters cannot be connected to with the current firmware. I could be wrong though on those details.

I just use your application almost daily because I switch between three different networks (home, school, family/friends). Having to rejoin through the stock menu and enter the lengthy passwords gets tedious and cuts down on playtime. The fact your app makes it a simple selection of previously connected speeds all that up and makes it a breeze. :)

I am overall enjoying Onion. I have heard of the other ones, but haven't spent much time researching them yet as Onion seems to be doing most of what I want/need, so I haven't felt compelled to dive into them yet. I appreciate you sharing them as alternatives to check out. :)

**Comment by XK9274** [comment]
Addressed in https://github.com/XK9274/better-wifi-miyoo/commit/1ed0d7e6af6617aa61c1e89beeedd9f78846a4cf
