### ISSUE TITLE
Option to toggle "disabled" for each network

### ISSUE THREAD

**Issue by MichaelRPowell** [XK9274/better-wifi-miyoo#3]
This is a question and possibly a feature request.

Unless someone has two networks overlapping in the same location, is there any reason for "disabled" for each network not in use? I know some operating systems do that automatically as well. I am curious what the impact is (processor/battery), but I didn't have much luck finding any information on my initial searches.

The reason I ask is that after some brief testing, it appears I can leave 3-4 networks without the "disabled" setting. Whenever I am near the appropriate network it connects without me having to open the application and choosing "Connect to a Stored Network". I assume most people might have different networks at home, work, school, and a family or friend's place. You could easily travel between those within a single day, so having all those common networks active makes it easy to pull out the Miyoo Mini Plus and play connected to the network.

In my mind, it might be nice to have a menu where you can toggle "disabled" for each network individually that is stored in the wpa_supplicant file. Any network a user frequently connects to could be left enabled, unless there is some known drawback to that idea?

Anyways, the program is still great, but just wanted to share this idea for possible improvement.

**Comment by XK9274** [comment]
Added in https://github.com/XK9274/better-wifi-miyoo/commit/a552005c081aa3f1e41040ac5fd8fbaa14b0c2b5 (and some in https://github.com/XK9274/better-wifi-miyoo/commit/1ed0d7e6af6617aa61c1e89beeedd9f78846a4cf)
