### ISSUE TITLE
How to install? Where is the zip?

### ISSUE THREAD

**Issue by codaroma** [XK9274/better-wifi-miyoo#6]
How to install? Where is the zip?
Readme says this...

_Usage
**Download the zip** Unzip Copy the BetterWifi folder to the App folder on your SDCARD (/App/BetterWifi/)_

But I can't find any zip file. Any clues?

**Comment by XK9274** [comment]
Download the main branch with the green "Code" button on the main GitHub page.

**Comment by codaroma** [comment]
got it thanks

Can I suggest adding this link in the readme?
https://github.com/XK9274/better-wifi-miyoo/archive/refs/heads/main.zip
